

-- 官方文档：https://dev.mysql.com/doc/refman/8.0/en/create-table.html
-- 查看建表语句
SHOW CREATE TABLE wms.`product`;

SHOW CREATE TABLE wms.`product_copy`

SELECT  COUNT(id) FROM wms.`product`;

SELECT  *  FROM wms.`product` LIMIT 100000,200000;
-- 耗时10s
SELECT DISTINCT(CreateTime) FROM wms.`product`;

SELECT DISTINCT(CreateTime) FROM wms.`product`
ORDER BY createTime

         --    一、date型换int型 
         -- SELECT UNIX_TIMESTAMP(‘2017-9-22 13:54:45’)

         -- 二、int型转date型 
         -- SELECT FROM_UNIXTIME(1506059685)
         
  -- SELECT   microsecond('2000-01-01 00:00:00');
         		
		SELECT   TO_DAYS('2000-01-01 00:00:00');
		
		SELECT   TO_DAYS('2000-01-01 12:00:00');
		
		SELECT TO_SECONDS ('2000-01-01 12:00:00');
		
-- 只取年月日去重 :在t内排序之后分组之后又乱序。在t外排序
SELECT DATE, COUNT(*) 'Count' FROM (
SELECT DATE_FORMAT(CreateTime,'%Y-%m-%d') 'Date'  FROM wms.`product`
) AS t
GROUP BY DATE
ORDER BY DATE 

-- 最好别用关键字
SELECT YearMonthDate ,COUNT(YearMonthDate) 'Count' FROM (
SELECT DATE_FORMAT(CreateTime,'%Y-%m-%d') YearMonthDate  FROM wms.`product`
ORDER BY CreateTime 
) AS t 
GROUP BY YearMonthDate

SELECT * FROM (
SELECT DATE_FORMAT(CreateTime,'%Y-%m-%d') 'Date'  FROM wms.`product`
ORDER BY CreateTime 
) AS t




SELECT DATE_FORMAT(CreateTime,'%Y-%m-%d') 'Date'  FROM wms.`product`
GROUP BY CreateTime
ORDER BY CreateTime 

-- 只取年月日去重
SELECT DISTINCT ( DATE_FORMAT(CreateTime,'%Y-%m-%d') ) 'Date'  FROM wms.`product`
ORDER BY CreateTime 

-- %Y  四位数字表示的年份
-- %y  两位数字表示的年份
SELECT DATE_FORMAT(NOW(),'%y-%m-%d') 'Date';

SELECT DATE_FORMAT(NOW(),'%Y-%m-%d') 'Date';

-- 创建分区
-- 分区方式：RANGE、LIST、HASH、KEY

-- 创建表指定分区
CREATE TABLE t1 (
    year_col  INT,
    some_data INT
)
PARTITION BY RANGE (year_col) (
    PARTITION p0 VALUES LESS THAN (2000),
    PARTITION p1 VALUES LESS THAN (2001),
    PARTITION p0 VALUES LESS THAN (2002),
    PARTITION p1 VALUES LESS THAN (2003),
    PARTITION p1 VALUES LESS THAN (2004),
    PARTITION p0 VALUES LESS THAN (2005),
    PARTITION p1 VALUES LESS THAN (2006),
    PARTITION p1 VALUES LESS THAN (2007),
    PARTITION p0 VALUES LESS THAN (2008),
    PARTITION p1 VALUES LESS THAN (2009),
    PARTITION p1 VALUES LESS THAN (2010),
    PARTITION p1 VALUES LESS THAN (2011),
    PARTITION p0 VALUES LESS THAN (2012),
    PARTITION p1 VALUES LESS THAN (2013),
    PARTITION p1 VALUES LESS THAN (2014),
    PARTITION p0 VALUES LESS THAN (2015),
    PARTITION p1 VALUES LESS THAN (2016),
    PARTITION p1 VALUES LESS THAN (2017),
    PARTITION p0 VALUES LESS THAN (2018),
    PARTITION p1 VALUES LESS THAN (2019),
    PARTITION p0 VALUES LESS THAN (2020),
    PARTITION p1 VALUES LESS THAN (2021),
    PARTITION p5 VALUES LESS THAN MAXVALUE
);

-- 不能在没有分区的表中创建分区，必须重新创建表
-- insert into 分区表 select * from 原始表; 
-- 在已分区的表中添加新的分区：更新表添加分区
ALTER TABLE wms.`product` ADD PARTITION (

    PARTITION p2000 VALUES LESS THAN (2000),
    PARTITION p2001 VALUES LESS THAN (2001),
    PARTITION p2002 VALUES LESS THAN (2002),
    PARTITION p2003 VALUES LESS THAN (2003),
    PARTITION p2004 VALUES LESS THAN (2004),
    PARTITION p2005 VALUES LESS THAN (2005),
    PARTITION p2006 VALUES LESS THAN (2006),
    PARTITION p2007 VALUES LESS THAN (2007),
    PARTITION p2008 VALUES LESS THAN (2008),
    PARTITION p2009 VALUES LESS THAN (2009),
    PARTITION p2010 VALUES LESS THAN (2010),
    PARTITION p2011 VALUES LESS THAN (2011),
    PARTITION p2012 VALUES LESS THAN (2012),
    PARTITION p2013 VALUES LESS THAN (2013),
    PARTITION p2014 VALUES LESS THAN (2014),
    PARTITION p2015 VALUES LESS THAN (2015),
    PARTITION p2016 VALUES LESS THAN (2016),
    PARTITION p2017 VALUES LESS THAN (2017),
    PARTITION p2018 VALUES LESS THAN (2018),
    PARTITION p2019 VALUES LESS THAN (2019),
    PARTITION p2020 VALUES LESS THAN (2020),
    PARTITION p2021 VALUES LESS THAN (2021),
    PARTITION p2022 VALUES LESS THAN MAXVALUE
);

-- 原表创建语句有约束
 USE wms;
  CREATE TABLE `productPartition` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
           `ID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
           `GUID` VARCHAR(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'guid',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
           `StockID` INT(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
           `BarCodeID` INT(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
           `SkuID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
           `ProductName` VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
           `ProductStyle` VARCHAR(50) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
           `Price` DECIMAL(10,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
           `CreateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
           `Status` SMALLINT(6) NOT NULL COMMENT '0、删除 1、正常',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
           `Count` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
           `ModifyTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
           `Timestamp` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
           PRIMARY KEY (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
           UNIQUE KEY `Index_Timestamp` (`Timestamp`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
           KEY `ProductStock` (`StockID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
           KEY `ProductBarCode` (`BarCodeID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
           KEY `ProductSku` (`SkuID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
           KEY `PRODUCT_INDEX_PRICE` (`Price`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
           KEY `PRODUCT_INDEX_PRODUCTMULTIPLE` (`ProductName`,`ProductStyle`,`CreateTime` DESC,`Price`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
           FULLTEXT KEY `fulltext_index` (`ProductName`,`ProductStyle`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
           CONSTRAINT `ProductBarCode` FOREIGN KEY (`BarCodeID`) REFERENCES `barcode` (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
           CONSTRAINT `ProductSku` FOREIGN KEY (`SkuID`) REFERENCES `sku` (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
           CONSTRAINT `ProductStock` FOREIGN KEY (`StockID`) REFERENCES `stock` (`ID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         ) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8   ;
         
         -- 复制表中发现没有约束: 表分区不能有全文索引
         -- range分区不能直接对日期型数据分区，所以要对分日期进行分区，需要变通一下，将日期转换成int型才行。
         --    一、date型换int型 
         -- SELECT UNIX_TIMESTAMP(‘2017-9-22 13:54:45’)

         -- 二、int型转date型 
         -- SELECT FROM_UNIXTIME(1506059685)

	
		
		
	   -- 复制表中发现没有约束: 表分区不能有全文索引
         -- range分区不能直接对日期型数据分区，所以要对分日期进行分区，需要变通一下，将日期转换成int型才行。	
         -- 分区列必须是包含主键中，设置联合主键 PRIMARY KEY (`ID`, `CreateTime` ),  
         -- 分区不能有时间戳信息UNIX_TIMESTAMP('2001-01-01 00:00:00')
         -- 分区名称必须唯一
         -- PARTITION p_max VALUES LESS THAN MAXVALUE   :MAXVALUE can only be used in last partition definition
	     CREATE TABLE `product_partition` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                `ID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                `GUID` VARCHAR(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'guid',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                `StockID` INT(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                `BarCodeID` INT(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                `SkuID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                `ProductName` VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                `ProductStyle` VARCHAR(50) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                `Price` DECIMAL(10,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                `CreateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                `Status` SMALLINT(6) NOT NULL COMMENT '0、删除 1、正常',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                `Count` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                `ModifyTime` DATETIME NOT NULL ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                `Timestamp` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                PRIMARY KEY (`ID`, `CreateTime` ),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                KEY `ProductStock` (`StockID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                KEY `ProductBarCode` (`BarCodeID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                KEY `ProductSku` (`SkuID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                KEY `PRODUCT_INDEX_PRICE` (`Price`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                KEY `PRODUCT_INDEX_PRODUCTMULTIPLE` (`ProductName`,`ProductStyle`,`CreateTime`,`Price`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
              ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4  
              PARTITION BY RANGE (TO_DAYS(`CreateTime`)) (
                 PARTITION p2000 VALUES LESS THAN (TO_DAYS('2000-01-01')),
		 PARTITION p2001 VALUES LESS THAN (TO_DAYS('2001-01-01')),
		  PARTITION p2002 VALUES LESS THAN (TO_DAYS('2002-01-01')),
		 PARTITION p2003 VALUES LESS THAN (TO_DAYS('2003-01-01')),
		  PARTITION p2004 VALUES LESS THAN (TO_DAYS('2004-01-01')),
		 PARTITION p2005 VALUES LESS THAN (TO_DAYS('2005-01-01')), 
		 PARTITION p2006 VALUES LESS THAN (TO_DAYS('2006-01-01')),
		 PARTITION p2007 VALUES LESS THAN (TO_DAYS('2007-01-01')),
		   PARTITION p2008 VALUES LESS THAN (TO_DAYS('2008-01-01')),
		 PARTITION p2009 VALUES LESS THAN (TO_DAYS('2009-01-01')),
		  PARTITION p2010 VALUES LESS THAN (TO_DAYS('2010-01-01')),
		 PARTITION p2011 VALUES LESS THAN (TO_DAYS('2011-01-01')),
		  PARTITION p2012 VALUES LESS THAN (TO_DAYS('2012-01-01')),
		 PARTITION p2013 VALUES LESS THAN (TO_DAYS('2013-01-01')), 
		 PARTITION p2014 VALUES LESS THAN (TO_DAYS('2014-01-01')),
		 PARTITION p2015 VALUES LESS THAN (TO_DAYS('2015-01-01')),
		  PARTITION p2016 VALUES LESS THAN (TO_DAYS('2016-01-01')), 
		 PARTITION p2017 VALUES LESS THAN (TO_DAYS('2017-01-01')),
		 PARTITION p2018 VALUES LESS THAN (TO_DAYS('2018-01-01')),
		  PARTITION p2019 VALUES LESS THAN (TO_DAYS('2019-01-01')), 
		 PARTITION p2020 VALUES LESS THAN (TO_DAYS('2020-01-01')),
		 PARTITION p2021 VALUES LESS THAN (TO_DAYS('2021-01-01'))
		-- PARTITION p_max VALUES LESS THAN MAXVALUE  
		); 
		
		-- 删除最大分区
		ALTER TABLE product_partition TRUNCATE PARTITION p2022;
		
		-- 添加分区:之前表分区不能设置最大值
		ALTER TABLE wms.`product_partition` ADD PARTITION (
                  PARTITION p2022 VALUES LESS THAN (TO_DAYS('2022-01-01'))
                 -- PARTITION p2023 VALUES LESS THAN MAXVALUE
               );
               
        
-- insert into 分区表 select * from 原始表;  UNIX_TIMESTAMP('2022-01-01 00:00:00')
USE wms;
 INSERT INTO product_partition SELECT * FROM product;
 
-- 删除分区：删除分区即删除数据。
DELETE FROM t1 WHERE year_col < 1991;
ALTER TABLE t1 TRUNCATE PARTITION p1, p3;


-- 只取年月日去重 
SELECT DATE, COUNT(*) 'Count' FROM (
SELECT DATE_FORMAT(CreateTime,'%Y-%m-%d') 'Date'  FROM wms.`product`
) AS t
GROUP BY DATE
ORDER BY DATE

-- 0.02s
SELECT  *  FROM wms.`product_partition` WHERE CreateTime<'2000-01-01';
-- 6.08s
SELECT  *  FROM wms.`product` WHERE CreateTime<'2000-01-01';


-- 在分区中查找：命中分区P2000
 EXPLAIN SELECT  *  FROM wms.`product_partition` WHERE CreateTime<'2000-01-01';
-- 在表中扫描
EXPLAIN SELECT  *  FROM wms.`product` WHERE CreateTime<'2000-01-01';



-- 查看表存储引擎
SHOW TABLE STATUS FROM wms WHERE NAME='product';


-- 获取表分区的ID   ：ID%3，Hash(ID)。ID取余，Hash操作。
 --  一、分区表 全局ID表
INSERT INTO `wms`.`global_id` ( `TableName`)
VALUES  ( 'TableName');
  
 SELECT  *  FROM  `wms`.`global_id`
 


-- 二、redis.increment 获取ID

-- 三、redis提前生成好一批ID放在队列里等待取






